- name: Delete volume in FlashBlade
  hosts: localhost
  gather_facts: no
  tasks:
  - name: delete volume '{{ fs_name }}'
    purefb_fs:
      name: '{{ fs_name }}'
      fb_url: '{{ fb_url }}'
      api_token: '{{ api_token }}'
      state: absent
      eradicate: '{{ answer }}'
