- name: Create clone from volume
  hosts: localhost
  gather_facts: no
  tasks:
  - name: create clone from volume '{{ vol_name }}'
    purefa_volume:
      name: '{{ vol_name }}'
      target: '{{ target_vol }}'
      state: present
      fa_url: '{{ fa_url }}'
      api_token: '{{ api_token }}'
