- name: Delete protection group in FlashArray
  hosts: localhost
  gather_facts: no
  tasks:
  - name: delete pg '{{ pg_name }}'
    purefa_pg:
      pgroup: '{{ pg_name }}'
      state: absent
      eradicate: '{{ answer }}'
      fa_url: '{{ fa_url }}'
      api_token: '{{ api_token }}'
