- name: Map Volume to host in FlashArray
  hosts: localhost
  gather_facts: no
  tasks:
  - name: map '{{ vol_name }}' to host '{{ host_name }}'
    purefa_host:
      host: '{{ host_name }}'
      volume: '{{ vol_name }}'
      fa_url: '{{ fa_url }}'
      api_token: '{{ api_token }}'
