- name: Create new iSCSI host in FlashArray
  hosts: localhost
  gather_facts: no
  tasks:
  - name: create new host '{{ host_name }}'
    purefa_host:
      host: '{{ host_name }}'
      protocol: iscsi
      iqn:
      - '{{ iqn_name }}'
      fa_url: '{{ fa_url }}'
      api_token: '{{ api_token }}'
