- name: Delete volume in FlashArray
  hosts: localhost
  gather_facts: no
  tasks:
  - name: delete volume '{{ vol_name }}'
    purefa_volume:
      name: '{{ vol_name }}'
      fa_url: '{{ fa_url }}'
      api_token: '{{ api_token }}'
      state: absent
      eradicate: '{{ answer }}'
