- name: Snapshot volume in FlashArray
  hosts: localhost
  gather_facts: no
  tasks:
  - name: snapshot volume '{{ vol_name }}'
    purefa_snap:
      name: '{{ vol_name }}'
      suffix: '{{ suffix }}'
      fa_url: '{{ fa_url }}'
      api_token: '{{ api_token }}'
      state: present
